name: scbrider
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.8+648

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  background_location: ^0.8.1
  battery: ^2.0.2
  carrier_info: 2.0.2
  connectivity_plus: ^1.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  file_picker: ^4.2.1
  firebase_analytics: ^8.3.2
  firebase_crashlytics: 2.2.1
  flutter:
    sdk: flutter
  flutter_app_lock: ^2.0.0
  flutter_html: ^2.1.2
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.23.0+1
  focus_detector: ^2.0.0
  geolocator: 7.6.1
  graphql_flutter: ^5.0.0
  image: ^3.0.4
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+1
  local_auth: ^1.1.7
  native_pdf_renderer: ^4.0.1
  open_file: ^3.2.1
  package_info: ^2.0.0
  path_provider: ^2.0.3
  permission_handler: ^8.3.0
  pin_code_fields: ^7.3.0
  platform_device_id: ^1.0.1
  provider: ^6.0.1
  rxdart: ^0.26.0
  safe_device: ^1.0.8
  scrollable_positioned_list: ^0.2.2
  shared_preferences: ^2.0.7
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.10
  web_socket_channel: ^2.1.0
  barcode_widget: ^2.0.1
  screenshot: ^1.2.3
  gallery_saver: ^2.3.1
  device_info: ^2.0.3
  camera: ^0.9.4+17
  #camera_camera: ^2.0.2
  slide_to_act: ^2.0.1
  flutter_file_dialog: ^2.3.0
  flutter_local_notifications: ^9.3.2
  package_info_plus: ^1.0.6
  store_checker: ^1.0.0

dependency_overrides:
  firebase_crashlytics_platform_interface: 3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  http: ^0.13.1
  image_test_utils: ^1.0.0
  mockito: ^3.0.0
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/illustrations/onboarding_assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Medium.ttf
    - family: IBMPlexSansThai
      fonts:
        - asset: assets/fonts/IBMPlexSansThai-Regular.ttf
